### ISSUE TITLE
使用的一些问题

### ISSUE THREAD

**Issue by junwen0814** [iceAnson/Android-Skin#1]
1 文章最后的那个gradle命令是怎么用的，是要cd到对应的那个皮肤module打出来吗，需不需要加../gradlew，我试了下好像都不行。
2 这个框架支持自定义View的自定义属性换肤吗，有的自定义view，他有自定义属性，属性就是设置颜色的，这个能换这个颜色吗。
3 我项目中有用到databinding，xml写的时候就会遇到
```
android:textColor="@{item.check?@color/common_label_blue_color:@color/common_tv_hint_color}"
```
这种情况就比较尴尬了，我试过几个皮肤框架，你这个会比其他的方便多了

**Comment by iceAnson** [comment]
1、就是正常的打包命令，我本地环境是mac，path配置了gradle 4.1;所以可以在Android-Skin目录下直接执行gradle :demo:skinone:assembleDebug即可生成apk;或者进入skinone目录执行gradle clean assembleDebug

2、可以无缝支持自定义控件，只要在xml布局里写上color,drawable之类的资源即可，和普通的view使用一样

3、databinding由于在编译时生成了代码，这个我试试看能否支持一下

**Comment by junwen0814** [comment]
第二个问题，不是系统的颜色属性哦，是类似余圆角的第三方控件，他自己定义的边框颜色这样的属性，这种可以支持xml换肤吗

**Comment by iceAnson** [comment]
明白了，我之后加个拓展支持吧

**Comment by iceAnson** [comment]
databinding 是调用了ViewDataBinding里的getColorFromResource来获取颜色的，然后在子类（ActivityDatabindingBinding extends ViewDataBinding）调用了setTextColor进行颜色设置的，无法进行换肤替换，除非采用插桩形式，目前暂不支持。

**Comment by junwen0814** [comment]
好的，谢谢

**Comment by iceAnson** [comment]
master代码自持自定义属性了
